import sqlmodel
"""Added optional billing_rate field to user model

Revision ID: 62df23f72630
Revises: 9b313d1a91e3
Create Date: 2026-06-18 11:44:16.019280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62df23f72630'
down_revision: Union[str, Sequence[str], None] = '9b313d1a91e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('billing_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'billing_rate')
    # ### end Alembic commands ###
