import sqlmodel
"""Made is_enabled in Device False by default

Revision ID: 9b313d1a91e3
Revises: 4190d27721b2
Create Date: 2026-06-15 18:08:28.879902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b313d1a91e3'
down_revision: Union[str, Sequence[str], None] = '4190d27721b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
