import sqlmodel
"""energy_limits

Revision ID: 9c048ffe09f9
Revises: 62df23f72630
Create Date: 2026-06-28 12:14:53.267859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c048ffe09f9'
down_revision: Union[str, Sequence[str], None] = '62df23f72630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('DAILY_LIMIT_REACHED', 'MONTHLY_LIMIT_REACHED', name='energyeventtype'), nullable=False),
    sa.Column('period', sa.Enum('DAILY', 'MONTHLY', name='energyeventperiod'), nullable=False),
    sa.Column('period_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kwh_at_event', sa.Float(), nullable=False),
    sa.Column('limit_kwh', sa.Float(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'event_type', 'period_key', name='uq_energy_event_device_type_period')
    )
    op.create_index(op.f('ix_energy_events_device_id'), 'energy_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_energy_events_user_id'), 'energy_events', ['user_id'], unique=False)
    op.add_column('devices', sa.Column('daily_limit_kwh', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('monthly_limit_kwh', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('auto_cutoff_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('devices', sa.Column('cutoff_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('devices', sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'cutoff_at')
    op.drop_column('devices', 'cutoff_reason')
    op.drop_column('devices', 'auto_cutoff_enabled')
    op.drop_column('devices', 'monthly_limit_kwh')
    op.drop_column('devices', 'daily_limit_kwh')
    op.drop_index(op.f('ix_energy_events_user_id'), table_name='energy_events')
    op.drop_index(op.f('ix_energy_events_device_id'), table_name='energy_events')
    op.drop_table('energy_events')
    # ### end Alembic commands ###
