"""add device timers and timer lock fields

Revision ID: c9ce541d13d7
Revises: 9c048ffe09f9
Create Date: 2026-07-27 13:25:15.439229

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ce541d13d7'
down_revision: Union[str, Sequence[str], None] = '9c048ffe09f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_timers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_timers_device_id'), 'device_timers', ['device_id'], unique=False)
    op.add_column('devices', sa.Column('timer_lock_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('devices', sa.Column('timer_locked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'timer_locked_at')
    op.drop_column('devices', 'timer_lock_reason')
    op.drop_index(op.f('ix_device_timers_device_id'), table_name='device_timers')
    op.drop_table('device_timers')
    # ### end Alembic commands ###
